### ISSUE TITLE
Can't preview images, archives etc after deps installed

### ISSUE THREAD

**Issue by leebrooks0** [hut/ranger#262]
I installed highlight, exiftool, atool and w3m from apt. I couldn't find pdftotext.
I restarted Ranger and I can't preview images or archives (.zip), or get syntax highlighting.

Am I missing something? Those are really kickass features!

I tried gnome-terminal and Terminator. I am running Linux Mint 17.

**Comment by randynobx** [comment]
Make sure that you have a scope.sh file under ~/.config/scope.sh

If you dont, you can have ranger generate a new one for you by running:

    ranger --copy-config scope

That should fix syntax highlighting, and probably archives; but image previews are a little more involved, and I haven't gotten it working on my system yet.

**Comment by elvis-sik** [comment]
Hi. I am not sure if this should go in a new issue or not.

I am able to preview images using caca-utils' tool on gnome-terminal, urxvt and xterm, but unable on all three to get the output from w3mimgdisplay.

I just installed ranger from source. I ran `ranger --copy-config all` and added the `set preview_images true` line to `rc.conf`. I thought maybe `img2txt` was the default preview method, and it was blocking `w3mimgdisplay`, so I uninstalled it to no effect. I also tried adding the folder with the `w3mimgdisplay` to `$PATH` without success. I searched through `scope.sh` and saw it makes no reference to `w3mimgdisplay` at all, but there is `img2txt` in there.

Otherwise, everything is fine, I can preview html, pdf, and code with syntax highlighting just fine.

**Comment by hut** [comment]
If w3mimgdispaly is not in `/usr/lib/w3m/w3mimgdisplay`, then correct the path by defining it through the W3MIMGDISPLAY_PATH environment variable. Does that help?

**Comment by elvis-sik** [comment]
The path is exactly that, but I set the env variable just to be sure, and also, in a bout of despair, tried rebooting. No good. I thought maybe by magic the video thumbnails would work

**Comment by Garviell** [comment]
I have the exact same issue.  Tried two different versions of ranger, no luck.

**Comment by hut** [comment]
closing due to old age. Chech the wiki for the tutorial on image previews ( https://github.com/hut/ranger/wiki/Image-Previews ) and reopen if the issue persists.

**Comment by elvis-sik** [comment]
[This](http://blog.z3bra.org/2014/01/images-in-terminal.html) works ok. I have all settings according to the wiki (I have a `scope.sh` and I have a `rc.conf` with `set preview_images true`. It doesn't work.

However, if I `export RANGER_LOAD_DEFAULT_RC=FALSE` and fire up ranger, it opens stuck. That is, I cannot do anything, except pressing `C-z` to suspend the job.

**Comment by hut** [comment]
Cool article you linked there.

Don't use `RANGER_LOAD_DEFAULT_RC=FALSE`. What's your OS?

**Comment by elvis-sik** [comment]
I use Arch. When I originally commented here I was on Ubuntu. I tried deleting all my old configs and running `ranger --copy-config all` and doing everything from the wiki and it worked! :smile:

**Comment by hut** [comment]
Awesome :D
