### ISSUE TITLE
Mount external drives?

### ISSUE THREAD

**Issue by Zekario** [hut/ranger#416]
I was wondering how to access external drives such as USB sticks. The Arch wiki says udev or udisks will let you do this (both of which I have installed), and they are available under /media or /run/media/$USER. I checked both of these for my USB and it showed up on neither. It shows up on other filemanagers like Thunar, and I was wondering how to do it with ranger.\

Am I missing a crucial step somewhere? Thanks for any help!

**Comment by pekkadebian** [comment]
command-line tool udisksctl

use "lsblk" to find external drives

udiskctl mount -b /dev/sdxY
and 
udiskctl unmount -b /dev/sdxY


Ranger  rc.conf "map gm cd /run/media"

**Comment by Zekario** [comment]
That works, thanks!

The command is udisksctl, not udiskctl. Just in case someone needs this.

I'm going to look into automatic mounting.

**Comment by dquinton** [comment]
I'm not sure if setting Thunar to manage disks inhibits udev or something, so that only after starting Thunar ext disks are mounted.  I noticed it once, but I don't use any gui file mgr now.

I run Openbox and [set up udevil](http://dquinton.github.io/debian-install/config/plain-openbox.html#6) to manage mounting removable drives - but u need to eject them
