### ISSUE TITLE
<C-h> does not function within tmux.

### ISSUE THREAD

**Issue by krompus** [hut/ranger#559]
I have remapped <C-h> to move the the tab on the left:

`map <C-h>     tab_move -1`

I'm not sure if it's a tmux bug or a ranger bug. I have no issues when I run ranger outside of tmux, but it's unresponsive inside.

Before, I had it mapped to the default "show hidden files", but that didn't work either. I've since started using `zh` instead.

Any idea what may be causing the issue? I'm asking the tmux people about it too.

**Comment by mrogalski** [comment]
Quite probably not-our-bug.
AFAIR `ctrl+h` is used as a delete/backspace character. Try to see what is sent to the terminal when You type `ctrl+h` -- You should be able to do this with `ctrl+v` which inserts literally (without interpreatation) whatever You type after it. Open bash, type `ctrl+v`+`ctrl+h` -- it should print `^H`.  If I do the same thing in tmux, it prints a `^?` -- which means that two different control characters are sent to the console. `^?` is a delete, `^H` is a ctrl+h which is then interpreted as whatever the terminal wants it to.

**Comment by krompus** [comment]
Well, it prints `^H` in a bare term *and* when I have tmux open. I've checked, and `C-h` isn't bound in my tmux config either.

**Comment by mrogalski** [comment]
Oh, sorry, ^H is not ctrl+h, it's the backspace character.
Try mapping <BS> instead of <c-h>.

**Comment by krompus** [comment]
Oh, you mean map `<BS>` to go tab-left? Well, I suppose I could, but I'd much rather use `C-h`, as I already use it globally; tmux, vim, pentadactyl...

Currently, I'm just using tab-right exclusively in ranger, which isn't the end of the world, but it's a little annoying.

I'm just trying to figure out if this is indeed a ranger bug or a tmux bug.

**Comment by mrogalski** [comment]
Open vim, go to insert mode, type `ctrl+v` `ctrl+h` and `ctrl+v` `backspace`. Then go to normal mode, and do a `ga` on that inputted characters.  For ^H:
```
<^H>  8,  Hex 08,  Octal 010
```
For ^?:
```
<^?>  127,  Hex 7f,  Octal 177
```
After consulting the almighty `man ascii`, we find that 
```
010   8     08    BS  '\b' (backspace)

177   127   7F    DEL
```
Therefore, based on the authority on the manuals, I claim that ^H is backspace, and ^? is delete.  But it is not mean the key delete or key backspace, it's just a name -- blame people who wrote this thing eons ago.  To convince You further on that some strange things happen:
```
 > echo -n "abc\b\bx"           
axc
 > echo -n "abc\b\bx" | wc 
      0       1       6
 > echo -n "abc\0177\0177x"        
abcx
 > echo -n "abc\0177\0177x" | wc
      0       1       6
```
^H means something like move the carriage one symbol to the left (a nondestructive delete, back-a-space), and ^? is reserved exclusively to mean erase a character.  

Now, to define things perfectly: when I shall type `<bs>` I mean a sequence of four characters.   If `ctrl+h` emits ^H and not ^?, then You can just do a `:map <bs> whatever` in vim and ranger to mean whatever You want them to.  Since Your terminals correctly emit ^? when You press the key backspace, then You don't have a problem -- only ctrl+h emits ^H (that is `<bs>`), and binding that to whatever You want should resolve the issue.

More on this in  and http://unix.stackexchange.com/questions/180087/why-pressing-ctrl-h-in-xterm-tmux-sends/180106 and http://www.ibb.net/~anne/keyboard.html

**Comment by krompus** [comment]
wat

...is works

Ahahaha, I think you've entirely out-nerded me! That's some confusing but very interesting stuff; thank you so much for sharing your knowledge and resolving my issue! :)

**Comment by yinflying** [comment]
Good!  This taught me much, I have solved the problem that <c-h> can not work for the map "set show_hidden!".

**Comment by kyawthusoe3142** [comment]
Debian out of the box doesn't have this problem. Arch has this problem. Does it mean Arch has a deficiency.
What should Arch do to fix this problem? Is this related to ncurses as pointed out in http://unix.stackexchange.com/questions/180087/why-pressing-ctrl-h-in-xterm-tmux-sends/180106?
I'm not quite sure. What's at fault here? Does anyone care to elaborate? I feel bad that Arch has this problem by default. Should I carry this to Arch's bug tracker?

**Comment by kyawthusoe3142** [comment]
Also <c-h> and <BS> are usable in Emacs ncurses. It's not in ranger.
