### ISSUE TITLE
What is a recommended way to set the default sorting style for a folder?

### ISSUE THREAD

**Issue by rbn42** [hut/ranger#561]
Hi,

I have this setting for ~/Downloads folder:
`setlocal path=~/Downloads sort mtime`

But with this setting on, I can no longer change the sorting style of the ~/Downloads folder during ranger running, like with this command:
`map os chain set sort=size;      set sort_reverse=False`

Thanks

**Comment by hut** [comment]
That's an unfortunate limitation of the way settings currently work.

Some ways to work around this:
* use `setintag` instead of `setlocal` so you can remove the tag temporarily when you want to change the sorting order. (see `setintag` and `TAGS` in man page)
* type `cs` to move to the largest file, and then `n` to walk through all the files in order of size, without having to change the sorting order
* fix the problem & write a patch :heart:

**Comment by rbn42** [comment]
Well, so you mean the sorting setting of the 'set' command during runtime is overwritten by the sorting setting of the 'setlocal' command in rc.conf?

I changed the sorting command from
`map os chain set sort=size; set sort_reverse=False`
to
`map os chain setlocal sort=size; setlocal sort_reverse=False`

And now it works. 
Thanks :-)
