### ISSUE TITLE
'G' don't go to the end of file in preview

### ISSUE THREAD

**Issue by adam8157** [hut/ranger#74]
'G' don't go to the end of file in preview, it almost acts as the same as "Ctrl f", but one more line forward.

**Comment by genkimarshall** [comment]
Just went and looked at this. Without going too deep, I tested on a large file. Specifically, `AUTHORS` in the root of the repo.
* I first noted that the above is still the case. Specifically, when `scope.sh` exists in `~/.config/ranger/`, `G` will work in preview, but otherwise `G` does not go to the end of the file. I then noted that it does work if you first travel all the way down to the bottom of the file. (I.e., you can do `g` from the bottom of the file, then `G` again and it will go down to the bottom). So it seemed to be that when `scope.sh` exists, the entire file is read in and correctly calculates the length, but when `scope.sh` does not exist, it only reads in what it needs to, and thus `G` only jumps to how far it has read.
* I found this to be the case when looking into the code.
* The method in question is [this one](https://github.com/hut/ranger/blob/master/ranger/gui/widgets/pager.py#L116).
* Let's say we're vertical. Then any move command while in the preview (pager) mode, will go to [this line](https://github.com/hut/ranger/blob/master/ranger/gui/widgets/pager.py#L129), calling `direction.move`.
* I found that the problem was that the call to `direction.move` passes a maximum that *should* be the length of the entire file in the preview. When `scope.sh` exists (i.e., using a preview script as @hut mentions), it is indeed the length of the entire file. However, when `scope.sh` does not exist, I found that the maximum was much too small. In fact, it was the number of lines of my terminal screen. So this confirmed the above.
* So looked a little further, when `scope.sh` exists, `len(self.lines)` will correctly be the length of the entire file, because it brings the entire file into memory and reads it correctly somewhere inside [`set_source`](https://github.com/hut/ranger/blob/master/ranger/gui/widgets/pager.py#L151). Also note that `self.source_is_stream` is `False`, so [this line](https://github.com/hut/ranger/blob/master/ranger/gui/widgets/pager.py#L128) is never reached.
* When `scope.sh` does not exist, then `self.source_is_stream` is `True`, and thus [`_get_line`](https://github.com/hut/ranger/blob/master/ranger/gui/widgets/pager.py#L192)  is called. This function is expected to not have the line when you scroll down, so it will go into the exception block [here](https://github.com/hut/ranger/blob/master/ranger/gui/widgets/pager.py#L196), and attempt to iterate the lines in `self.source`. But again, this will not bring in the entire file. Because it is lazily read.

So, not sure what you want to be done here, @hut? I'm willing to send a PR to fix it.

**Comment by genkimarshall** [comment]
Also, would appreciate a tip on how you normally go about debugging. I just ended up using the `log` function, because `pdb` doesn't play nicely with `ncurses` I found, and `pdb` doesn't have the ability to set another `tty` as the `IO` terminal like `gdb` does.

**Comment by hut** [comment]
Thanks for looking into this!

I think the best way to solve this is to detect where the cursor will be after the movement by doing the `self.scroll_begin = direction.move(...)` command with a maximum value of, say, `self.scroll_begin + 10000` instead of `len(self.lines)`. Then call `self._get_line(self.scroll_begin + self.hei)` *afterwards* to read in as many lines as necessary. Lastly we need to ensure that `self.scroll_begin` doesn't exceed the maximum number of lines. We could use the `direction.move()` function again with the new maximum value or just do a `self.scroll_begin = max(min(pos, len(self.lines) - self.hei), 0))` like `direction.move()` would've done at the end.

I guess by writing this, I figured out how to fix this myself. I leave it up to you to decide if you want to implement it and send a PR or leave it to me, I don't mind either way.

Also, winpdb has suited me well before, it spawns the process in a console.

**Comment by genkimarshall** [comment]
Ah great, thank you!

> I guess by writing this, I figured out how to fix this myself. I leave it
> up to you to decide if you want to implement it and send a PR or leave it
> to me, I don't mind either way.

It sounds like you understand it best, so to avoid any unnecessary back and
forth, yes, could you make the fix please?

> Also, winpdb has suited me well before, it spawns the process in a
> console.

Cool, will check it out, thank you.

**Comment by huyz** [comment]
Did this regress for anyone else? Hitting `G` doesn't go to the end. It also doesn't just gone page. It seems to do in-between
